// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDcbwavawNlhPRTEbb04-jUeGeYfWdNoPg',
    appId: '1:460969578586:web:d2abac6335589182b44863',
    messagingSenderId: '460969578586',
    projectId: 'universalrecommendationsys',
    authDomain: 'universalrecommendationsys.firebaseapp.com',
    storageBucket: 'universalrecommendationsys.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA4kNuv8kJjzWAmApXi3R1mf5jg57X_wno',
    appId: '1:460969578586:android:1d60abcefde0e232b44863',
    messagingSenderId: '460969578586',
    projectId: 'universalrecommendationsys',
    storageBucket: 'universalrecommendationsys.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCSBptsOJP6r0b50vnueuVJkkQog-0sX-U',
    appId: '1:460969578586:ios:5e5a8b6ffa9b3846b44863',
    messagingSenderId: '460969578586',
    projectId: 'universalrecommendationsys',
    storageBucket: 'universalrecommendationsys.appspot.com',
    iosBundleId: 'com.example.universalRecommendationSystem',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCSBptsOJP6r0b50vnueuVJkkQog-0sX-U',
    appId: '1:460969578586:ios:02bbf23da6c41b01b44863',
    messagingSenderId: '460969578586',
    projectId: 'universalrecommendationsys',
    storageBucket: 'universalrecommendationsys.appspot.com',
    iosBundleId: 'com.example.universalRecommendationSystem.RunnerTests',
  );
}
